version: '3'
services:
  dict-nginx:
    image: nginx:latest
    container_name: "dict-nginx"
    depends_on:
      - dict-php
    ports:
      - 10089:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/www/logs
      - ./src:/www/html
    environment:
      TZ: 'Europe/Amsterdam'

  dict-php:
    container_name: "dict-php"
    build:
      context: ./docker/php
    volumes:
      - ./src:/www/html:rw
      - ./data:/www/data:rw
      - ./logs:/www/logs
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /www
